---
services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    network_mode: "host"
    volumes:
      - ./config:/config
    restart: unless-stopped
